### ISSUE TITLE
NodeMCU compatibility

### ISSUE THREAD

**Issue by Bodmer** [duinoWitchery/hd44780#1]
Hello World runs fine.

In I2CexpDiag the software watchdog gets triggered. Simplest way to illustrate this is to run the sketch on a bare NodeMCU (no display connected) and watch the Serial Monitor output.

yeild() or delay(0) needed periodically to cooperatively multitask in setup().

Note: Cycling around the loop() automatically inserts yeild(), while(1) not a good idea.

**Comment by bperrybap** [comment]
From my brief read on the subject the default watchdog is 1 second?
setup() can be  quite lengthy with no calls to yield() or delay() so I'm assuming this occurs before loop()  ever gets called, which displays the uptime.

Since I don't have any h/w yet, how does a watch dog trigger behave?
Does the board hang, blink any LEDs? restart???

I'll need to go look and see when yield() was added to the IDE to see how messy using that would be, but if delay(0) works, that may be the better option.
I'll have to go look at the Arduino core code to see if delay(0) freaks out on older IDEs.

Seems like this will be easy to fix.

**Comment by bperrybap** [comment]
The trickier thing is how to handle fatalError() which designed to intentionally lock up the system.
There are basically two choices:
- let the watchdog happen, which will cause a restart, losing any potential information on the display
- disable the watchdog to allow the code to hang and blink an LED.

I'm leaning twards the 2nd option and disabling the watch dog in the fatalError() routine.
The reason being that hanging can be useful to see how long the system operated.

Any suggestions?

**Comment by Bodmer** [comment]
The watchdog restarts the sketch when fatal error is encountered as no builtin LED is defined. This fixes it:
	while(1){ yield(); } // spin and do nothing

showI2Cdevices() needs a yield() in the search loop too because if SDA and SCL are pulled low by a load then all addresses report an error and it reboots on the watchdog:

_Scanning i2c bus for devices..
 Unknown error at address 0x08
 Unknown error at address 0x09
  ...
  ...
 Unknown error at address 0x44
 Unknown error 
Soft WDT reset_

  Perhaps a "stuck low" test could be added.

**Comment by bperrybap** [comment]
This is still an issue (actually more than one) that needs to be resolved so I will leave it open until I resolve them.
using yield() is not an option as it didn't exist prior to Arduino 1.5.1 BETA so I'll use delay() to allow the code to compile on pre 1.5 IDEs.

**Comment by bperrybap** [comment]
Great idea on the stuck test BTW. I'll definitely add that to diag sketch.

**Comment by bperrybap** [comment]
I2CexpDiag should run properly on ESP8266 platforms now as of release 0.8.2
Still need to resolve the fatalError() routines in all the other example sketches.

**Comment by bperrybap** [comment]
This should now be fully resolved as of release 0.8.4
