### ISSUE TITLE
LCD Address

### ISSUE THREAD

**Issue by WRichardR** [duinoWitchery/hd44780#7]
Hello,
Pardon me for my format . This is my first post ever to ask for help concerning Arduino. I Will learn and improve.

I have tried your library to replace another.
This is the library it replaced. It worked reasonably well before.
//  #include<LiquidCrystal_I2C.h>
The actual replacement went well, except to when compiling. 

The hd44780.h showed as it should. Farther down, for the LCD address
LiquidCrystal_I2C lcd(0x27, 20, 4);
the error showed
'LiquidCrystal_I2C' does not name a type.

Please, I do not understand this. Can you give me any suggestions to fix this ?

Wayne

**Comment by bperrybap** [comment]
This is not an issue with the hd44780 library.
Github issues are for issues with the library rather than getting help/support.
Help for this type of issue is best provided by using the Arduino forum.
Simply, create a new topic/thread in the "Displays" section and you can get the help you need.

As to your issue, you must update your sketch code to use the hd44780_I2Cexp i/o class provided by the hd44780 library.
See the included hd44780_I2Cexp i/o class examples for the needed header include files and how to declare your lcd object.

If you need more help/support open a new topic/thread on the Arduino forum.
